"""
Channel-specific response formatters.
PDF requirement: agent/formatters.py as separate module.
"""

def format_for_email(message: str, ticket_id: str = "") -> str:
    """Format response for Email channel — formal, detailed."""
    return f"""Dear Customer,

{message}

Best regards,
TechCorp AI Support Team
---
Ticket Reference: {ticket_id}
This response was generated by our AI assistant.
For complex issues, reply to this email to request human support."""

def format_for_whatsapp(message: str) -> str:
    """Format response for WhatsApp — concise, max 300 chars preferred."""
    if len(message) > 300:
        message = message[:297] + "..."
    return f"{message}\n\n📱 Type 'human' for live support."

def format_for_web_form(message: str) -> str:
    """Format response for Web Form — semi-formal, clear."""
    return f"""{message}

---
Need more help? Reply to this message or visit our support portal."""

def split_whatsapp_message(response: str, max_length: int = 1600) -> list[str]:
    """
    Split long WhatsApp responses into multiple messages.
    Twilio max is 1600 chars per message.
    PDF Exercise 2.2 requirement.
    """
    if len(response) <= max_length:
        return [response]

    messages = []
    while response:
        if len(response) <= max_length:
            messages.append(response)
            break
        break_point = response.rfind('. ', 0, max_length)
        if break_point == -1:
            break_point = response.rfind(' ', 0, max_length)
        if break_point == -1:
            break_point = max_length
        messages.append(response[:break_point + 1].strip())
        response = response[break_point + 1:].strip()

    return messages

def format_for_channel(
    message: str,
    channel: str,
    ticket_id: str = ""
) -> str:
    """Route to correct formatter based on channel."""
    if channel == "email":
        return format_for_email(message, ticket_id)
    elif channel == "whatsapp":
        return format_for_whatsapp(message)
    else:
        return format_for_web_form(message)
